spring.application.name=user-service

server.port=8081

#IRVR
spring.mvc.view.suffix=.jsp


#DMDS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql:3306/smartshop
#spring.datasource.url=jdbc:mysql://localhost:3307/userdb
spring.datasource.username=root
spring.datasource.password=root

#LSFB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update  


eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true